#define BT_RX ??
#define BT_TX ??

#define SRF_ECHO_1 3
#define SRF_TRIG_1 2
#define SRF_ECHO_2 1
#define SRF_TRIG_2 0
#define SRF_ECHO_3 9
#define SRF_TRIG_3 10
#define SRF_ECHO_4 13
#define SRF_TRIG_4 12
#define SRF_ECHO_5 11
#define SRF_TRIG_5 10
#define SRF_ECHO_6 16
#define SRF_TRIG_6 17

#define LEFT_FRONT_KNEE 40
#define LEFT_FRONT_HORI 42
#define LEFT_FRONT_VERT 44
#define LEFT_MIDDLE_KNEE 46
#define LEFT_MIDDLE_HORI 48
#define LEFT_MIDDLE_VERT 50
#define LEFT_REAR_KNEE 52
#define LEFT_REAR_HORI 14
#define LEFT_REAR_VERT 15
#define RIGHT_FRONT_KNEE 38
#define RIGHT_FRONT_HORI 36
#define RIGHT_FRONT_VERT 34
#define RIGHT_MIDDLE_KNEE 32
#define RIGHT_MIDDLE_HORI 30
#define RIGHT_MIDDLE_VERT 28
#define RIGHT_REAR_KNEE 26
#define RIGHT_REAR_HORI 24
#define RIGHT_REAR_VERT 22

